/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin/activity-logs'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminServicesCustomRouteImport } from './routes/admin/services-custom'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CheckoutManualRouteImport } from './routes/checkout/manual'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard/documents'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as GigsIndexRouteImport } from './routes/gigs/index'
import { Route as GigsSlugRouteImport } from './routes/gigs/$slug'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes.$quoteId'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ServicesRequestQuoteRouteImport } from './routes/services/request-quote'
import { Route as AdminAboutIndexRouteImport } from './routes/admin/about/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogPostSlugRouteImport } from './routes/admin/blog/$postSlug'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients/$clientId'
import { Route as AdminDocumentsIndexRouteImport } from './routes/admin/documents/index'
import { Route as AdminGigsIndexRouteImport } from './routes/admin/gigs/index'
import { Route as AdminGigsGigSlugRouteImport } from './routes/admin/gigs/$gigSlug'
import { Route as AdminGigsNewRouteImport } from './routes/admin/gigs/new'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminMessagesIndexRouteImport } from './routes/admin/messages/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminPartnersIndexRouteImport } from './routes/admin/partners/index'
import { Route as AdminPartnersAnalyticsRouteImport } from './routes/admin/partners/analytics'
import { Route as AdminPartnersNewRouteImport } from './routes/admin/partners/new'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsProjectSlugRouteImport } from './routes/admin/projects/$projectSlug'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminServicesServiceSlugRouteImport } from './routes/admin/services/$serviceSlug'
import { Route as AdminServicesNewRouteImport } from './routes/admin/services/new'
import { Route as AdminServicesQuotesRouteImport } from './routes/admin/services/quotes'
import { Route as AdminServicesRequestsRouteImport } from './routes/admin/services/requests'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsEmailTemplatesRouteImport } from './routes/admin/settings/email-templates'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin/testimonials/index'
import { Route as AdminTestimonialsNewRouteImport } from './routes/admin/testimonials/new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersPermissionsRouteImport } from './routes/admin/users/permissions'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'
import { Route as GigsCategorySlugRouteImport } from './routes/gigs/category/$slug'
import { Route as ProjectsCategorySlugRouteImport } from './routes/projects/category/$slug'
import { Route as AdminBlogEditPostSlugRouteImport } from './routes/admin/blog/edit/$postSlug'
import { Route as AdminGigsEditGigSlugRouteImport } from './routes/admin/gigs/edit/$gigSlug'
import { Route as AdminPagesEditPageSlugRouteImport } from './routes/admin/pages/edit/$pageSlug'
import { Route as AdminPartnersEditPartnerIdRouteImport } from './routes/admin/partners/edit/$partnerId'
import { Route as AdminProjectsEditProjectSlugRouteImport } from './routes/admin/projects/edit/$projectSlug'
import { Route as AdminServicesEditServiceSlugRouteImport } from './routes/admin/services/edit/$serviceSlug'
import { Route as AdminServicesQuotesQuoteIdRouteImport } from './routes/admin/services/quotes.$quoteId'
import { Route as AdminTestimonialsEditTestimonialIdRouteImport } from './routes/admin/testimonials/edit/$testimonialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesCustomRoute = AdminServicesCustomRouteImport.update({
  id: '/services-custom',
  path: '/services-custom',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutManualRoute = CheckoutManualRouteImport.update({
  id: '/checkout/manual',
  path: '/checkout/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsSlugRoute = GigsSlugRouteImport.update({
  id: '/gigs/$slug',
  path: '/gigs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRequestQuoteRoute = ServicesRequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminAboutIndexRoute = AdminAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogPostSlugRoute = AdminBlogPostSlugRouteImport.update({
  id: '/blog/$postSlug',
  path: '/blog/$postSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsIndexRoute = AdminDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGigsIndexRoute = AdminGigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGigsGigSlugRoute = AdminGigsGigSlugRouteImport.update({
  id: '/gigs/$gigSlug',
  path: '/gigs/$gigSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGigsNewRoute = AdminGigsNewRouteImport.update({
  id: '/gigs/new',
  path: '/gigs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesIndexRoute = AdminMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersIndexRoute = AdminPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersAnalyticsRoute = AdminPartnersAnalyticsRouteImport.update({
  id: '/partners/analytics',
  path: '/partners/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersNewRoute = AdminPartnersNewRouteImport.update({
  id: '/partners/new',
  path: '/partners/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsProjectSlugRoute =
  AdminProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesServiceSlugRoute =
  AdminServicesServiceSlugRouteImport.update({
    id: '/services/$serviceSlug',
    path: '/services/$serviceSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesQuotesRoute = AdminServicesQuotesRouteImport.update({
  id: '/services/quotes',
  path: '/services/quotes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRequestsRoute = AdminServicesRequestsRouteImport.update({
  id: '/services/requests',
  path: '/services/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsEmailTemplatesRoute =
  AdminSettingsEmailTemplatesRouteImport.update({
    id: '/settings/email-templates',
    path: '/settings/email-templates',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsNewRoute = AdminTestimonialsNewRouteImport.update({
  id: '/testimonials/new',
  path: '/testimonials/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersPermissionsRoute = AdminUsersPermissionsRouteImport.update({
  id: '/users/permissions',
  path: '/users/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsCategorySlugRoute = GigsCategorySlugRouteImport.update({
  id: '/gigs/category/$slug',
  path: '/gigs/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCategorySlugRoute = ProjectsCategorySlugRouteImport.update({
  id: '/projects/category/$slug',
  path: '/projects/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogEditPostSlugRoute = AdminBlogEditPostSlugRouteImport.update({
  id: '/blog/edit/$postSlug',
  path: '/blog/edit/$postSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGigsEditGigSlugRoute = AdminGigsEditGigSlugRouteImport.update({
  id: '/gigs/edit/$gigSlug',
  path: '/gigs/edit/$gigSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesEditPageSlugRoute = AdminPagesEditPageSlugRouteImport.update({
  id: '/pages/edit/$pageSlug',
  path: '/pages/edit/$pageSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersEditPartnerIdRoute =
  AdminPartnersEditPartnerIdRouteImport.update({
    id: '/partners/edit/$partnerId',
    path: '/partners/edit/$partnerId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProjectsEditProjectSlugRoute =
  AdminProjectsEditProjectSlugRouteImport.update({
    id: '/projects/edit/$projectSlug',
    path: '/projects/edit/$projectSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesEditServiceSlugRoute =
  AdminServicesEditServiceSlugRouteImport.update({
    id: '/services/edit/$serviceSlug',
    path: '/services/edit/$serviceSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesQuotesQuoteIdRoute =
  AdminServicesQuotesQuoteIdRouteImport.update({
    id: '/$quoteId',
    path: '/$quoteId',
    getParentRoute: () => AdminServicesQuotesRoute,
  } as any)
const AdminTestimonialsEditTestimonialIdRoute =
  AdminTestimonialsEditTestimonialIdRouteImport.update({
    id: '/testimonials/edit/$testimonialId',
    path: '/testimonials/edit/$testimonialId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/services-custom': typeof AdminServicesCustomRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/manual': typeof CheckoutManualRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/request-quote': typeof ServicesRequestQuoteRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/$postSlug': typeof AdminBlogPostSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/gigs/$gigSlug': typeof AdminGigsGigSlugRoute
  '/admin/gigs/new': typeof AdminGigsNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/analytics': typeof AdminPartnersAnalyticsRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/projects/$projectSlug': typeof AdminProjectsProjectSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/$serviceSlug': typeof AdminServicesServiceSlugRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/services/quotes': typeof AdminServicesQuotesRouteWithChildren
  '/admin/services/requests': typeof AdminServicesRequestsRoute
  '/admin/settings/email-templates': typeof AdminSettingsEmailTemplatesRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/users/permissions': typeof AdminUsersPermissionsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/gigs/category/$slug': typeof GigsCategorySlugRoute
  '/projects/category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/about/': typeof AdminAboutIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/documents/': typeof AdminDocumentsIndexRoute
  '/admin/gigs/': typeof AdminGigsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/blog/edit/$postSlug': typeof AdminBlogEditPostSlugRoute
  '/admin/gigs/edit/$gigSlug': typeof AdminGigsEditGigSlugRoute
  '/admin/pages/edit/$pageSlug': typeof AdminPagesEditPageSlugRoute
  '/admin/partners/edit/$partnerId': typeof AdminPartnersEditPartnerIdRoute
  '/admin/projects/edit/$projectSlug': typeof AdminProjectsEditProjectSlugRoute
  '/admin/services/edit/$serviceSlug': typeof AdminServicesEditServiceSlugRoute
  '/admin/services/quotes/$quoteId': typeof AdminServicesQuotesQuoteIdRoute
  '/admin/testimonials/edit/$testimonialId': typeof AdminTestimonialsEditTestimonialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/services-custom': typeof AdminServicesCustomRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/manual': typeof CheckoutManualRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/request-quote': typeof ServicesRequestQuoteRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gigs': typeof GigsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blog/$postSlug': typeof AdminBlogPostSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/gigs/$gigSlug': typeof AdminGigsGigSlugRoute
  '/admin/gigs/new': typeof AdminGigsNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/analytics': typeof AdminPartnersAnalyticsRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/projects/$projectSlug': typeof AdminProjectsProjectSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/$serviceSlug': typeof AdminServicesServiceSlugRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/services/quotes': typeof AdminServicesQuotesRouteWithChildren
  '/admin/services/requests': typeof AdminServicesRequestsRoute
  '/admin/settings/email-templates': typeof AdminSettingsEmailTemplatesRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/users/permissions': typeof AdminUsersPermissionsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/gigs/category/$slug': typeof GigsCategorySlugRoute
  '/projects/category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/about': typeof AdminAboutIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/documents': typeof AdminDocumentsIndexRoute
  '/admin/gigs': typeof AdminGigsIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/messages': typeof AdminMessagesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/partners': typeof AdminPartnersIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/blog/edit/$postSlug': typeof AdminBlogEditPostSlugRoute
  '/admin/gigs/edit/$gigSlug': typeof AdminGigsEditGigSlugRoute
  '/admin/pages/edit/$pageSlug': typeof AdminPagesEditPageSlugRoute
  '/admin/partners/edit/$partnerId': typeof AdminPartnersEditPartnerIdRoute
  '/admin/projects/edit/$projectSlug': typeof AdminProjectsEditProjectSlugRoute
  '/admin/services/edit/$serviceSlug': typeof AdminServicesEditServiceSlugRoute
  '/admin/services/quotes/$quoteId': typeof AdminServicesQuotesQuoteIdRoute
  '/admin/testimonials/edit/$testimonialId': typeof AdminTestimonialsEditTestimonialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/services-custom': typeof AdminServicesCustomRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/manual': typeof CheckoutManualRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/gigs/$slug': typeof GigsSlugRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/request-quote': typeof ServicesRequestQuoteRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog/$postSlug': typeof AdminBlogPostSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/gigs/$gigSlug': typeof AdminGigsGigSlugRoute
  '/admin/gigs/new': typeof AdminGigsNewRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/partners/analytics': typeof AdminPartnersAnalyticsRoute
  '/admin/partners/new': typeof AdminPartnersNewRoute
  '/admin/projects/$projectSlug': typeof AdminProjectsProjectSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/$serviceSlug': typeof AdminServicesServiceSlugRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/services/quotes': typeof AdminServicesQuotesRouteWithChildren
  '/admin/services/requests': typeof AdminServicesRequestsRoute
  '/admin/settings/email-templates': typeof AdminSettingsEmailTemplatesRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/users/permissions': typeof AdminUsersPermissionsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/gigs/category/$slug': typeof GigsCategorySlugRoute
  '/projects/category/$slug': typeof ProjectsCategorySlugRoute
  '/admin/about/': typeof AdminAboutIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/documents/': typeof AdminDocumentsIndexRoute
  '/admin/gigs/': typeof AdminGigsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/blog/edit/$postSlug': typeof AdminBlogEditPostSlugRoute
  '/admin/gigs/edit/$gigSlug': typeof AdminGigsEditGigSlugRoute
  '/admin/pages/edit/$pageSlug': typeof AdminPagesEditPageSlugRoute
  '/admin/partners/edit/$partnerId': typeof AdminPartnersEditPartnerIdRoute
  '/admin/projects/edit/$projectSlug': typeof AdminProjectsEditProjectSlugRoute
  '/admin/services/edit/$serviceSlug': typeof AdminServicesEditServiceSlugRoute
  '/admin/services/quotes/$quoteId': typeof AdminServicesQuotesQuoteIdRoute
  '/admin/testimonials/edit/$testimonialId': typeof AdminTestimonialsEditTestimonialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$slug'
    | '/auth'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/admin/activity-logs'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/services-custom'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/checkout/manual'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/support'
    | '/dashboard/tasks'
    | '/gigs/$slug'
    | '/invoices/$id'
    | '/projects/$slug'
    | '/quotes/$quoteId'
    | '/services/$slug'
    | '/services/request-quote'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/gigs/'
    | '/partners/'
    | '/projects/'
    | '/admin/blog/$postSlug'
    | '/admin/blog/new'
    | '/admin/clients/$clientId'
    | '/admin/gigs/$gigSlug'
    | '/admin/gigs/new'
    | '/admin/pages/new'
    | '/admin/partners/analytics'
    | '/admin/partners/new'
    | '/admin/projects/$projectSlug'
    | '/admin/projects/new'
    | '/admin/services/$serviceSlug'
    | '/admin/services/new'
    | '/admin/services/quotes'
    | '/admin/services/requests'
    | '/admin/settings/email-templates'
    | '/admin/testimonials/new'
    | '/admin/users/permissions'
    | '/api/public/stripe-webhook'
    | '/blog/category/$slug'
    | '/gigs/category/$slug'
    | '/projects/category/$slug'
    | '/admin/about/'
    | '/admin/blog/'
    | '/admin/clients/'
    | '/admin/documents/'
    | '/admin/gigs/'
    | '/admin/invoices/'
    | '/admin/media/'
    | '/admin/messages/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/admin/projects/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/testimonials/'
    | '/admin/users/'
    | '/admin/blog/edit/$postSlug'
    | '/admin/gigs/edit/$gigSlug'
    | '/admin/pages/edit/$pageSlug'
    | '/admin/partners/edit/$partnerId'
    | '/admin/projects/edit/$projectSlug'
    | '/admin/services/edit/$serviceSlug'
    | '/admin/services/quotes/$quoteId'
    | '/admin/testimonials/edit/$testimonialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/admin/activity-logs'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/services-custom'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/checkout/manual'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/support'
    | '/dashboard/tasks'
    | '/gigs/$slug'
    | '/invoices/$id'
    | '/projects/$slug'
    | '/quotes/$quoteId'
    | '/services/$slug'
    | '/services/request-quote'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/gigs'
    | '/partners'
    | '/projects'
    | '/admin/blog/$postSlug'
    | '/admin/blog/new'
    | '/admin/clients/$clientId'
    | '/admin/gigs/$gigSlug'
    | '/admin/gigs/new'
    | '/admin/pages/new'
    | '/admin/partners/analytics'
    | '/admin/partners/new'
    | '/admin/projects/$projectSlug'
    | '/admin/projects/new'
    | '/admin/services/$serviceSlug'
    | '/admin/services/new'
    | '/admin/services/quotes'
    | '/admin/services/requests'
    | '/admin/settings/email-templates'
    | '/admin/testimonials/new'
    | '/admin/users/permissions'
    | '/api/public/stripe-webhook'
    | '/blog/category/$slug'
    | '/gigs/category/$slug'
    | '/projects/category/$slug'
    | '/admin/about'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/documents'
    | '/admin/gigs'
    | '/admin/invoices'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/blog/edit/$postSlug'
    | '/admin/gigs/edit/$gigSlug'
    | '/admin/pages/edit/$pageSlug'
    | '/admin/partners/edit/$partnerId'
    | '/admin/projects/edit/$projectSlug'
    | '/admin/services/edit/$serviceSlug'
    | '/admin/services/quotes/$quoteId'
    | '/admin/testimonials/edit/$testimonialId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$slug'
    | '/auth'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/admin/activity-logs'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/services-custom'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/checkout/manual'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/support'
    | '/dashboard/tasks'
    | '/gigs/$slug'
    | '/invoices/$id'
    | '/projects/$slug'
    | '/quotes/$quoteId'
    | '/services/$slug'
    | '/services/request-quote'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/gigs/'
    | '/partners/'
    | '/projects/'
    | '/admin/blog/$postSlug'
    | '/admin/blog/new'
    | '/admin/clients/$clientId'
    | '/admin/gigs/$gigSlug'
    | '/admin/gigs/new'
    | '/admin/pages/new'
    | '/admin/partners/analytics'
    | '/admin/partners/new'
    | '/admin/projects/$projectSlug'
    | '/admin/projects/new'
    | '/admin/services/$serviceSlug'
    | '/admin/services/new'
    | '/admin/services/quotes'
    | '/admin/services/requests'
    | '/admin/settings/email-templates'
    | '/admin/testimonials/new'
    | '/admin/users/permissions'
    | '/api/public/stripe-webhook'
    | '/blog/category/$slug'
    | '/gigs/category/$slug'
    | '/projects/category/$slug'
    | '/admin/about/'
    | '/admin/blog/'
    | '/admin/clients/'
    | '/admin/documents/'
    | '/admin/gigs/'
    | '/admin/invoices/'
    | '/admin/media/'
    | '/admin/messages/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/admin/projects/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/testimonials/'
    | '/admin/users/'
    | '/admin/blog/edit/$postSlug'
    | '/admin/gigs/edit/$gigSlug'
    | '/admin/pages/edit/$pageSlug'
    | '/admin/partners/edit/$partnerId'
    | '/admin/projects/edit/$projectSlug'
    | '/admin/services/edit/$serviceSlug'
    | '/admin/services/quotes/$quoteId'
    | '/admin/testimonials/edit/$testimonialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutManualRoute: typeof CheckoutManualRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  GigsSlugRoute: typeof GigsSlugRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GigsIndexRoute: typeof GigsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  GigsCategorySlugRoute: typeof GigsCategorySlugRoute
  ProjectsCategorySlugRoute: typeof ProjectsCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services-custom': {
      id: '/admin/services-custom'
      path: '/services-custom'
      fullPath: '/admin/services-custom'
      preLoaderRoute: typeof AdminServicesCustomRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/manual': {
      id: '/checkout/manual'
      path: '/checkout/manual'
      fullPath: '/checkout/manual'
      preLoaderRoute: typeof CheckoutManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/gigs'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$slug': {
      id: '/gigs/$slug'
      path: '/gigs/$slug'
      fullPath: '/gigs/$slug'
      preLoaderRoute: typeof GigsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/request-quote': {
      id: '/services/request-quote'
      path: '/request-quote'
      fullPath: '/services/request-quote'
      preLoaderRoute: typeof ServicesRequestQuoteRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/about/': {
      id: '/admin/about/'
      path: '/about'
      fullPath: '/admin/about/'
      preLoaderRoute: typeof AdminAboutIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$postSlug': {
      id: '/admin/blog/$postSlug'
      path: '/blog/$postSlug'
      fullPath: '/admin/blog/$postSlug'
      preLoaderRoute: typeof AdminBlogPostSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents/': {
      id: '/admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminDocumentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gigs/': {
      id: '/admin/gigs/'
      path: '/gigs'
      fullPath: '/admin/gigs/'
      preLoaderRoute: typeof AdminGigsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gigs/$gigSlug': {
      id: '/admin/gigs/$gigSlug'
      path: '/gigs/$gigSlug'
      fullPath: '/admin/gigs/$gigSlug'
      preLoaderRoute: typeof AdminGigsGigSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gigs/new': {
      id: '/admin/gigs/new'
      path: '/gigs/new'
      fullPath: '/admin/gigs/new'
      preLoaderRoute: typeof AdminGigsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages/': {
      id: '/admin/messages/'
      path: '/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AdminMessagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners/': {
      id: '/admin/partners/'
      path: '/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AdminPartnersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners/analytics': {
      id: '/admin/partners/analytics'
      path: '/partners/analytics'
      fullPath: '/admin/partners/analytics'
      preLoaderRoute: typeof AdminPartnersAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners/new': {
      id: '/admin/partners/new'
      path: '/partners/new'
      fullPath: '/admin/partners/new'
      preLoaderRoute: typeof AdminPartnersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/$projectSlug': {
      id: '/admin/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/admin/projects/$projectSlug'
      preLoaderRoute: typeof AdminProjectsProjectSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/$serviceSlug': {
      id: '/admin/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/admin/services/$serviceSlug'
      preLoaderRoute: typeof AdminServicesServiceSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/services/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/quotes': {
      id: '/admin/services/quotes'
      path: '/services/quotes'
      fullPath: '/admin/services/quotes'
      preLoaderRoute: typeof AdminServicesQuotesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/requests': {
      id: '/admin/services/requests'
      path: '/services/requests'
      fullPath: '/admin/services/requests'
      preLoaderRoute: typeof AdminServicesRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/email-templates': {
      id: '/admin/settings/email-templates'
      path: '/settings/email-templates'
      fullPath: '/admin/settings/email-templates'
      preLoaderRoute: typeof AdminSettingsEmailTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials/new': {
      id: '/admin/testimonials/new'
      path: '/testimonials/new'
      fullPath: '/admin/testimonials/new'
      preLoaderRoute: typeof AdminTestimonialsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/permissions': {
      id: '/admin/users/permissions'
      path: '/users/permissions'
      fullPath: '/admin/users/permissions'
      preLoaderRoute: typeof AdminUsersPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/category/$slug': {
      id: '/gigs/category/$slug'
      path: '/gigs/category/$slug'
      fullPath: '/gigs/category/$slug'
      preLoaderRoute: typeof GigsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/category/$slug': {
      id: '/projects/category/$slug'
      path: '/projects/category/$slug'
      fullPath: '/projects/category/$slug'
      preLoaderRoute: typeof ProjectsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/edit/$postSlug': {
      id: '/admin/blog/edit/$postSlug'
      path: '/blog/edit/$postSlug'
      fullPath: '/admin/blog/edit/$postSlug'
      preLoaderRoute: typeof AdminBlogEditPostSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gigs/edit/$gigSlug': {
      id: '/admin/gigs/edit/$gigSlug'
      path: '/gigs/edit/$gigSlug'
      fullPath: '/admin/gigs/edit/$gigSlug'
      preLoaderRoute: typeof AdminGigsEditGigSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/edit/$pageSlug': {
      id: '/admin/pages/edit/$pageSlug'
      path: '/pages/edit/$pageSlug'
      fullPath: '/admin/pages/edit/$pageSlug'
      preLoaderRoute: typeof AdminPagesEditPageSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners/edit/$partnerId': {
      id: '/admin/partners/edit/$partnerId'
      path: '/partners/edit/$partnerId'
      fullPath: '/admin/partners/edit/$partnerId'
      preLoaderRoute: typeof AdminPartnersEditPartnerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/edit/$projectSlug': {
      id: '/admin/projects/edit/$projectSlug'
      path: '/projects/edit/$projectSlug'
      fullPath: '/admin/projects/edit/$projectSlug'
      preLoaderRoute: typeof AdminProjectsEditProjectSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/edit/$serviceSlug': {
      id: '/admin/services/edit/$serviceSlug'
      path: '/services/edit/$serviceSlug'
      fullPath: '/admin/services/edit/$serviceSlug'
      preLoaderRoute: typeof AdminServicesEditServiceSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/quotes/$quoteId': {
      id: '/admin/services/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/admin/services/quotes/$quoteId'
      preLoaderRoute: typeof AdminServicesQuotesQuoteIdRouteImport
      parentRoute: typeof AdminServicesQuotesRoute
    }
    '/admin/testimonials/edit/$testimonialId': {
      id: '/admin/testimonials/edit/$testimonialId'
      path: '/testimonials/edit/$testimonialId'
      fullPath: '/admin/testimonials/edit/$testimonialId'
      preLoaderRoute: typeof AdminTestimonialsEditTestimonialIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminServicesQuotesRouteChildren {
  AdminServicesQuotesQuoteIdRoute: typeof AdminServicesQuotesQuoteIdRoute
}

const AdminServicesQuotesRouteChildren: AdminServicesQuotesRouteChildren = {
  AdminServicesQuotesQuoteIdRoute: AdminServicesQuotesQuoteIdRoute,
}

const AdminServicesQuotesRouteWithChildren =
  AdminServicesQuotesRoute._addFileChildren(AdminServicesQuotesRouteChildren)

interface AdminRouteRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminServicesCustomRoute: typeof AdminServicesCustomRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogPostSlugRoute: typeof AdminBlogPostSlugRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminGigsGigSlugRoute: typeof AdminGigsGigSlugRoute
  AdminGigsNewRoute: typeof AdminGigsNewRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminPartnersAnalyticsRoute: typeof AdminPartnersAnalyticsRoute
  AdminPartnersNewRoute: typeof AdminPartnersNewRoute
  AdminProjectsProjectSlugRoute: typeof AdminProjectsProjectSlugRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminServicesServiceSlugRoute: typeof AdminServicesServiceSlugRoute
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminServicesQuotesRoute: typeof AdminServicesQuotesRouteWithChildren
  AdminServicesRequestsRoute: typeof AdminServicesRequestsRoute
  AdminSettingsEmailTemplatesRoute: typeof AdminSettingsEmailTemplatesRoute
  AdminTestimonialsNewRoute: typeof AdminTestimonialsNewRoute
  AdminUsersPermissionsRoute: typeof AdminUsersPermissionsRoute
  AdminAboutIndexRoute: typeof AdminAboutIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminDocumentsIndexRoute: typeof AdminDocumentsIndexRoute
  AdminGigsIndexRoute: typeof AdminGigsIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminMessagesIndexRoute: typeof AdminMessagesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPartnersIndexRoute: typeof AdminPartnersIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminBlogEditPostSlugRoute: typeof AdminBlogEditPostSlugRoute
  AdminGigsEditGigSlugRoute: typeof AdminGigsEditGigSlugRoute
  AdminPagesEditPageSlugRoute: typeof AdminPagesEditPageSlugRoute
  AdminPartnersEditPartnerIdRoute: typeof AdminPartnersEditPartnerIdRoute
  AdminProjectsEditProjectSlugRoute: typeof AdminProjectsEditProjectSlugRoute
  AdminServicesEditServiceSlugRoute: typeof AdminServicesEditServiceSlugRoute
  AdminTestimonialsEditTestimonialIdRoute: typeof AdminTestimonialsEditTestimonialIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminServicesCustomRoute: AdminServicesCustomRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogPostSlugRoute: AdminBlogPostSlugRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminGigsGigSlugRoute: AdminGigsGigSlugRoute,
  AdminGigsNewRoute: AdminGigsNewRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminPartnersAnalyticsRoute: AdminPartnersAnalyticsRoute,
  AdminPartnersNewRoute: AdminPartnersNewRoute,
  AdminProjectsProjectSlugRoute: AdminProjectsProjectSlugRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminServicesServiceSlugRoute: AdminServicesServiceSlugRoute,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminServicesQuotesRoute: AdminServicesQuotesRouteWithChildren,
  AdminServicesRequestsRoute: AdminServicesRequestsRoute,
  AdminSettingsEmailTemplatesRoute: AdminSettingsEmailTemplatesRoute,
  AdminTestimonialsNewRoute: AdminTestimonialsNewRoute,
  AdminUsersPermissionsRoute: AdminUsersPermissionsRoute,
  AdminAboutIndexRoute: AdminAboutIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminDocumentsIndexRoute: AdminDocumentsIndexRoute,
  AdminGigsIndexRoute: AdminGigsIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminMessagesIndexRoute: AdminMessagesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPartnersIndexRoute: AdminPartnersIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminBlogEditPostSlugRoute: AdminBlogEditPostSlugRoute,
  AdminGigsEditGigSlugRoute: AdminGigsEditGigSlugRoute,
  AdminPagesEditPageSlugRoute: AdminPagesEditPageSlugRoute,
  AdminPartnersEditPartnerIdRoute: AdminPartnersEditPartnerIdRoute,
  AdminProjectsEditProjectSlugRoute: AdminProjectsEditProjectSlugRoute,
  AdminServicesEditServiceSlugRoute: AdminServicesEditServiceSlugRoute,
  AdminTestimonialsEditTestimonialIdRoute:
    AdminTestimonialsEditTestimonialIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesRequestQuoteRoute: typeof ServicesRequestQuoteRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesRequestQuoteRoute: ServicesRequestQuoteRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutManualRoute: CheckoutManualRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  GigsSlugRoute: GigsSlugRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  GigsIndexRoute: GigsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  GigsCategorySlugRoute: GigsCategorySlugRoute,
  ProjectsCategorySlugRoute: ProjectsCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
